### ISSUE TITLE
Regression: Failure to generate report when the db is empty and there is no data to parse

### ISSUE THREAD

**Issue by gpoo** [MetricsGrimoire/MailingListStats#58]
When running with a new database an no data, for example: `

```python
$ ./mlstats --db-driver=sqlite --db-name=bar.db
0 messages analyzed
0 messages stored in database bar.db
0 messages ignored by the parser
INFO: Everything seems to be ok.
Traceback (most recent call last):
  File "./mlstats", line 38, in <module>
    pymlstats.start()
  File "/home/gpoo/code/research/ml/mailingliststat/pymlstats/__init__.py", line 172, in start
    quiet, force, web_user, web_password, compressed_dir)
  File "/home/gpoo/code/research/ml/mailingliststat/pymlstats/main.py", line 204, in __init__
    report.print_brief_report(report_filename=report_filename)
  File "/home/gpoo/code/research/ml/mailingliststat/pymlstats/db/report.py", line 336, in print_brief_report
    column_length = self.determine_longest_values(messages_by_domain, callbacks)
  File "/home/gpoo/code/research/ml/mailingliststat/pymlstats/db/report.py", line 264, in determine_longest_values
    num_of_attributes = len(keyed_tuple[0])
IndexError: list index out of range
```

This is a regression introduced in faf89b09ff99c4c

**Comment by gpoo** [comment]
FWIW, this could also happen when processing an mbox which `mlstats` is unable to retrieve data and the `db` is still empty).

Running without anything to parse is useful to get reports.

**Comment by gpoo** [comment]
Commit df8cab72 fixes this one.
