### ISSUE TITLE
ImportError: No module named 'main' when I run python setup.py install

### ISSUE THREAD

**Issue by SaaShah** [MetricsGrimoire/MailingListStats#76]
> python setup.py install
```
Traceback (most recent call last):
  File "setup.py", line 37, in <module>
    from pymlstats.version import mlstats_version
  File "/home/mrx/src/ccm/CodeComMerg/MailingListStats/pymlstats/__init__.py", line 37, in <module>
    from main import Application
ImportError: No module named 'main'
```

I'm using python Python 3.5.2

Do I need to have 2.7 for it or is there any other problem ?

**Comment by acs** [comment]
@SaadBinShahid you can try https://github.com/grimoirelab/perceval which is the new collection platform developed by Bitergia which supports mailing lists analysis.

I think that MailingListStats works only with python 2.7 but not sure about it.

**Comment by gpoo** [comment]
Indeed. Only Python 2.x.

There are some modules used that are not available in 3.x.

**Comment by SaaShah** [comment]
Ahh.. I hope you guys port it to 3.x soon. 

Thank you & Good luck !
